"""
tests/test_spec_contract.py — SPEC-Contract TDD Scaffold
=========================================================
AUTO-GENERATED by SSI Step 2.4 (SKILL.md §Step 2.4)

Status: Partially RED — stubs raise NotImplementedError until contract verified.
        GREEN tests validate actual SPEC contracts.

Run only spec-marked tests:
    pytest tests/test_spec_contract.py -m spec -v

Run all (including stubs — expected failures):
    pytest tests/test_spec_contract.py -v --tb=short
"""

import json
import pytest
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# GREEN: verifiable immediately from schema/scripts (no subprocess needed)
# ---------------------------------------------------------------------------

@pytest.mark.spec
def test_gate_result_schema_required_fields():
    """SPEC: harness_gate_result.schema.json must define score, quality_complete, dimensions as required."""
    schema_path = REPO_ROOT / "schemas" / "harness_gate_result.schema.json"
    assert schema_path.exists(), f"Schema not found: {schema_path}"
    schema = json.loads(schema_path.read_text())
    required = schema.get("required", [])
    assert "score" in required, "SPEC: 'score' must be required in GateResult schema"
    assert "quality_complete" in required, "SPEC: 'quality_complete' must be required in GateResult schema"
    assert "dimensions" in required, "SPEC: 'dimensions' must be required in GateResult schema"


@pytest.mark.spec
def test_config_loader_weight_normalization():
    """SPEC: normalize_weights must produce enabled-dimension weights summing to 1.0."""
    import sys
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from config_loader import normalize_weights  # type: ignore

    cfg = {
        "dimensions": {
            "a": {"weight": 3, "enabled": True},
            "b": {"weight": 7, "enabled": True},
            "c": {"weight": 5, "enabled": False},  # disabled — excluded from sum
        }
    }
    result = normalize_weights(cfg)
    enabled_weights = [
        d["weight"] for d in result["dimensions"].values()
        if d.get("enabled", False)
    ]
    total = sum(enabled_weights)
    assert abs(total - 1.0) < 1e-6, f"SPEC: weights must sum to 1.0, got {total}"


@pytest.mark.spec
def test_score_py_overall_meets_target_field():
    """SPEC: compute_overall_score must return 'quality_complete' key."""
    import sys
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from score import compute_overall_score  # type: ignore

    scores = {
        "linting": {"score": 95.0},
        "type_safety": {"score": 88.0},
    }
    fake_config = {
        "quality": {"score_gate": 80},
        "dimensions": {
            "linting": {"enabled": True, "weight": 0.5, "target": 90},
            "type_safety": {"enabled": True, "weight": 0.5, "target": 85},
        },
    }
    result = compute_overall_score(scores, fake_config)
    assert "quality_complete" in result, "SPEC: compute_overall_score must return 'quality_complete'"
    assert "overall_score" in result, "SPEC: compute_overall_score must return 'overall_score'"


@pytest.mark.spec
def test_runner_cli_args_schema():
    """SPEC: runner.main() must accept --config, --root, --output args."""
    import subprocess, sys
    proc = subprocess.run(
        [sys.executable, "-m", "software_self_improvement.runner", "--help"],
        capture_output=True, text=True, cwd=str(REPO_ROOT)
    )
    help_text = proc.stdout + proc.stderr
    assert "--config" in help_text, "SPEC: runner must expose --config arg"
    assert "--root" in help_text, "SPEC: runner must expose --root arg"
    assert "--output" in help_text, "SPEC: runner must expose --output arg"


# ---------------------------------------------------------------------------
# RED stubs — raise NotImplementedError until contract verified end-to-end
# ---------------------------------------------------------------------------

@pytest.mark.spec
@pytest.mark.xfail(reason="TDD stub: verify runner exit code against real gate run")
def test_runner_exit_0_on_quality_complete():
    """SPEC: runner exits 0 when quality_complete=True, 1 otherwise."""
    raise NotImplementedError(
        "TDD stub — implement after first real gate run confirms exit code contract"
    )


@pytest.mark.spec
@pytest.mark.xfail(reason="TDD stub: verify issue_tracker idempotency on duplicate findings")
def test_issue_tracker_idempotent_add():
    """SPEC: adding the same finding twice yields the same issue ID (idempotent)."""
    raise NotImplementedError(
        "TDD stub — implement after issue_tracker de-dup logic verified"
    )
